# DefaultParticle 仅在武器没有任何粒子特效 Lore 时生效
# 设置为 NULL 则没有默认粒子
DefaultParticle: WITCH_MAGIC

# 以下注释为插件使用者提供指令参考
# 粒子代号                  名字翻译
#
# AMBIENT_ENTITY_EFFECT    环境实体效果
# ANGRY_VILLAGER           愤怒的村民
# BARRIER                  障壁
# BLOCK                    方块
# BLOCK_CRACK              方块破碎
# BLOCK_DUST               方块尘埃
# BUBBLE                   气泡
# BUBBLE_COLUMN_UP         向上气泡柱
# CLOUD                    云
# CRIT                     暴击
# CRIT_MAGIC               魔法暴击
# DAMAGE_INDICATOR         伤害指示
# DRAGON_BREATH            龙息
# DRIP_WATER               水滴落
# DRIP_LAVA                岩浆滴落
# DUST                     彩尘
# DUST_COLOR_TRANSITION    彩尘颜色过渡
# EFFECT                   效果
# ELDER_GUARDIAN_TELEPORT  长者守卫者传送
# ENCHANTMENT_TABLE        附魔台效果
# ENCHANT                  附魔
# END_ROD                  末地杆
# ENTITY_EFFECT            实体效果
# EXPLOSION_NORMAL         正常爆炸
# EXPLOSION_LARGE          大爆炸
# EXPLOSION_HUGE           巨大爆炸
# FALLING_DUST             下落尘埃
# FIREWORKS_SPARK          烟花发射
# FIREWORK                 烟花
# FLAME                    火焰
# HAPPY_VILLAGER           开心的村民
# HEART                    爱心
# INSTANT_EFFECT           即时效果
# ITEM_CRACK               物品破碎
# ITEM_TAKE                物品获取
# LAVA                     岩浆
# LARGE_SMOKE              大烟雾
# MAGIC_CRIT               魔法暴击
# MOB_APPEARANCE           怪物出现
# MOBSPAWNER_FLAMES        刷怪笼火焰
# NOTE                     音符
# PORTAL                   传送门
# RAIN                     雨
# REDSTONE                 红石尘埃
# SLIME                    粘液
# SMOKE_NORMAL             正常烟雾
# SMOKE_LARGE              大烟雾
# SPELL                    魔法
# SPELL_INSTANT            即时魔法
# SPELL_MOB                怪物魔法
# SPELL_MOB_AMBIENT        怪物环境魔法
# SPELL_WITCH              女巫魔法
# SPIT                     吐痰（不常用）
# SQUID_INK                鱿鱼墨水
# SNEEZE                   打喷嚏
# CAMPFIRE_COSY_SMOKE      篝火舒适烟雾
# CAMPFIRE_SIGNAL_SMOKE    篝火信号烟雾
# COMPOSTER                堆肥器效果
# FLASH                    闪光
# FALLING_LAVA             下落岩浆
# FALLING_WATER            下落水
# FALLING_HONEY            下落蜂蜜
# FALLING_NECTAR           下落花蜜
# FALLING_OBSIDIAN_TEAR    下落黑曜石泪
# LANDING_LAVA             岩浆着陆
# LANDING_HONEY            蜂蜜着陆
# LANDING_OBSIDIAN_TEAR    黑曜石泪着陆
# LANDING_WATER            水着陆
# REVERSE_PORTAL           反转传送门
# SOUL_FIRE_FLAME          灵魂火焰
# SOUL                     灵魂
# WHITE_ASH                白灰
# WITHER_ROSE              凋零玫瑰
# WITHER                   凋零
# FALLING_WATER            下落水
# FALLING_HONEY            下落蜂蜜
# FALLING_OBSIDIAN_TEAR    下落黑曜石泪
# FALLING_NECTAR           下落花蜜
# FALLING_LAVA             下落岩浆
# LANDING_LAVA             岩浆着陆
# LANDING_HONEY            蜂蜜着陆
# LANDING_OBSIDIAN_TEAR    黑曜石泪着陆
# REVERSE_PORTAL           反转传送门
# SOUL_FIRE_FLAME          灵魂火焰
# SOUL                     灵魂
# WHITE_ASH                白灰
# LEGACY_BLOCK_CRACK       旧版方块破碎
# LEGACY_BLOCK_DUST        旧版方块尘埃
# LEGACY_FALLING_DUST      旧版下落尘埃